// src/lib/db/seed.ts
import { db } from './client.js';
import { expenseSeries } from './schema.js';
import { SeriesStatus, FrequencyUnit } from '../../data.js';

type SeedExpenseTemplate = {
  name: string;
  provider?: string | null;
  type?: string | null;
  status?: SeriesStatus.Active | SeriesStatus.Paused | SeriesStatus.Canceled;
  frequencyInterval: number;
  frequencyUnit: FrequencyUnit.Week | FrequencyUnit.Month | FrequencyUnit.Year;
  paymentMethod?: string | null;
  amountCents: number;
  contactEmail?: string | null;
  portalUrl?: string | null;
  renewalDate?: string | null;
  nextDate?: string |null;
  verifiedDate?: string | null;
  createdAt?: string;
  updatedAt?: string | null;
};

// Helper to convert dollar amounts to integer cents
const dollarsToCents = (amount: number): number =>
  Math.round(amount * 100);

// Your seed data with amountCents converted, no emails/urls/renewals yet
const seedData: SeedExpenseTemplate[] = [
  {
    "name": "TEST ROW",
    "provider": "MyISP",
    "type": "utility",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Week,
    "paymentMethod": "online payment",
    "amountCents": 1000,
    "contactEmail": "billing@myisp.example",
    "portalUrl": "https://myisp.example",
    "nextDate": null,
    "renewalDate": "2025-09-01",
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Powershop",
    "provider": "Powershop",
    "type": "Utility",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "direct debit",
    "amountCents": 30000,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": "2025-08-21",
    "updatedAt": null
  },
  {
    "name": "Skinny Broadband",
    "provider": "Skinny",
    "type": "Utility",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "CC 1481",
    "amountCents": 10500,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": "2025-09-12",
    "renewalDate": null,
    "verifiedDate": "2025-08-21",
    "updatedAt": null
  },
  {
    "name": "Watercare",
    "provider": "Watercare",
    "type": "Utility",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "online payment",
    "amountCents": 6600,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "AC Rates Oaktree",
    "provider": "Auckland Council",
    "type": "Property",
    "status": SeriesStatus.Active,
    "frequencyInterval": 3,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "online payment",
    "amountCents": 89240,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": "2025-08-29",
    "renewalDate": "2025-08-29",
    "verifiedDate": "2025-08-21",
    "updatedAt": null
  },
  {
    "name": "AC Rates - Sunnyside",
    "provider": "Auckland Council",
    "type": "Property",
    "status": SeriesStatus.Active,
    "frequencyInterval": 3,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "online payment",
    "amountCents": 71239,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": "2025-08-29",
    "renewalDate": "2025-08-29",
    "verifiedDate": "2025-08-21",
    "updatedAt": null
  },
  {
    "name": "AA Insurance KMU151",
    "provider": "AA Insurance",
    "type": "Insurance",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "online payment",
    "amountCents": 69899,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "AA Insurance House",
    "provider": "AA Insurance",
    "type": "Insurance",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "Manual",
    "amountCents": 193859,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "AA Insurance Contents",
    "provider": "AA Insurance",
    "type": "Insurance",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "online payment",
    "amountCents": 54586,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Southern Cross Health",
    "provider": "Southern Cross",
    "type": "Health",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "direct debit",
    "amountCents": 30991,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Southern Cross Pet",
    "provider": "Southern Cross",
    "type": "Insurance",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "direct debit",
    "amountCents": 4799,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "AC Pools/Leisure - James",
    "provider": "Auckland Council",
    "type": "Sport/Hobby",
    "status": SeriesStatus.Canceled,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "direct debit",
    "amountCents": 7735,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Flow Academy",
    "provider": "Flow Academy",
    "type": "Sport/Hobby",
    "status": SeriesStatus.Active,
    "frequencyInterval": 3,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "online payment",
    "amountCents": 53000,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Music",
    "provider": "Modern Music Learning",
    "type": "Sport/Hobby",
    "status": SeriesStatus.Active,
    "frequencyInterval": 3,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "online payment",
    "amountCents": 40250,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Amazon Web Services",
    "provider": "Amazon Web Services",
    "type": "Internet Service",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "CC 1481",
    "amountCents": 1000,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Google One",
    "provider": "Google",
    "type": "Internet Service",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "CC 1481",
    "amountCents": 4999,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Google YouTubePremium",
    "provider": "Google",
    "type": "Entertainment",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "CC 1481",
    "amountCents": 2999,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": "2025-08-20",
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Iwantmyname",
    "provider": "Iwantmyname",
    "type": "Internet Service",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "CC 1481",
    "amountCents": 20000,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Microsoft Office 365",
    "provider": "Microsoft",
    "type": "Internet Service",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "CC 1481",
    "amountCents": 2232,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Netflix",
    "provider": "Netflix",
    "type": "Entertainment",
    "status": SeriesStatus.Canceled,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "CC 1481",
    "amountCents": 2799,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Microsoft Gamepass",
    "provider": "Microsoft",
    "type": "Entertainment",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "Manual",
    "amountCents": 0,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Disney+",
    "provider": "Disney Plus",
    "type": "Entertainment",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "CC 1481",
    "amountCents": 0,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Chico Grooming",
    "provider": "Barking Mad",
    "type": "Pet",
    "status": SeriesStatus.Active,
    "frequencyInterval": 6,
    "frequencyUnit": FrequencyUnit.Week,
    "paymentMethod": "Cash",
    "amountCents": 9000,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": "2025-08-21",
    "updatedAt": null
  },
  {
    "name": "School Fees",
    "provider": "Sherwood School",
    "type": "Education",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "online payment",
    "amountCents": 133550,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": "2026-02-01",
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "Will Orthodontist",
    "provider": "Dr Kimberly Tomlins",
    "type": "Health",
    "status": SeriesStatus.Canceled,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "auto payment",
    "amountCents": 36000,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "2Degrees",
    "provider": "2 Degrees",
    "type": "Utility",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "CC 1481",
    "amountCents": 1900,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": null,
    "updatedAt": null
  },
  {
    "name": "95a Oaktree Mortgage",
    "provider": "ASB",
    "type": "Loan",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Month,
    "paymentMethod": "auto payment",
    "amountCents": 240000,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": "2025-09-20",
    "renewalDate": null,
    "verifiedDate": "2025-08-21",
    "updatedAt": null
  },
  {
    "name": "Groceries",
    "provider": "Groceries",
    "type": "Groceries",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Week,
    "paymentMethod": "CC 1481",
    "amountCents": 40000,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": "2025-08-24",
    "renewalDate": null,
    "verifiedDate": "2025-08-21",
    "updatedAt": null
  },
  {
    "name": "AA membership",
    "provider": "AA Membership",
    "type": "Car",
    "status": SeriesStatus.Active,
    "frequencyInterval": 1,
    "frequencyUnit": FrequencyUnit.Year,
    "paymentMethod": "CC 1481",
    "amountCents": 7425,
    "contactEmail": null,
    "portalUrl": null,
    "nextDate": null,
    "renewalDate": null,
    "verifiedDate": "2025-08-21",
    "updatedAt": null
  }
] ;

export async function seed() {
  for (const expense of seedData) {
    await db.insert(expenseSeries).values(expense);
  }
  console.log('Seed complete!');
}

seed().catch(console.error);
